Adding Zoom and ColorSub_C/M/Y GDTF attributes, Pigtail settings, catch several crash errors
hugoaboud/blenderDMX pull request #18
Opened 2023-01-03 14:00 UTC by vanous

This adds several things:

* initial Zoom support
* initial ColorSub_C/M/Y support
* fixed the ColorAdd_R/G/B attribute support (not sure how this worked before... perhaps the original devices used R, G, B instead of the GDTF attributes...?)
* added Pigtail settings - this is not updated in realtime but only during adding/editing of a device
* catch several crash errors

Please let me know if i miss some of the formats or variable camelCasing.

2023-01-04 00:50 UTC, hugoaboud requested changes
Great job! I have a few comments and questions, but overall it looks very good.

2023-01-04 14:51 UTC, vanous commented on gdtf.py
> +        z=obj.dimensions.z
uh, i forgot python has this shorthand :)

2023-01-04 14:54 UTC, vanous commented on gdtf.py
> +                if 'Pigtail' in geom.model:
There can be multiple Pigtails easily. Larger linear devices indicate where input/outputs are (if on each side of the device) other devices might be plug-able in the base and then also in the yoke (screen carriers).

2023-01-04 15:01 UTC, vanous commented on gdtf.py
> -                obj_child.scale[0] *= scale[0]
Wow, my bad, thank you for catching this. Apologies.

2023-01-04 15:08 UTC, vanous commented
OK, this should be ready now.

2023-01-06 00:29 UTC, hugoaboud approved these changes

2023-01-06 00:32 UTC, hugoaboud commented
LGTM

2023-01-06 00:32 UTC, merged